postgres:
  host: localhost
  port: 5435
  dbname: transactions
  user: postgres
  password: password

http:
  host: localhost
  port: 8009

kafka:
  brokers: localhost:9092
  writetopic: new_transactions
  readtopic: processed_transactions
  groupid: transactions