postgres:
  host: postgres
  port: 5432
  dbname: transactions
  user: postgres
  password: password

http:
  host: 0.0.0.0
  port: 8009

kafka:
  brokers: kafka:9092
  writetopic: new_transactions
  readtopic: processed_transactions
  groupid: transactions