version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8009:8009"
    depends_on:
      - postgres
      - kafka
    networks:
      - kafka_network
    entrypoint: ["/bin/sh", "-c", "sleep 30 && ./transactistream"]

  mocksrv:
    build:
      context: ./mocktstream/
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - app
    networks:
      - kafka_network
    entrypoint: ["/bin/sh", "-c", "sleep 35 && ./mocktstream"]

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transactions
    ports:
      - "5435:5432"
    networks:
      - kafka_network

  zookeeper:
    image: zookeeper:3.7
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka_network

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge
