version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: transPostgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transactions
    ports:
      - "5435:5432"
